### ISSUE TITLE
USER STORY: Deploy Site

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#1]
As a **Developer**, I can **deploy the website early** so that I can **avoid any technical issues or stress later in the project**

**Acceptance Criteria:**

- The project must be deployed to Heroku
- The code must be stored in GitHub
- The code must be written on GitPod
- The database must use an external database like ElephantSQL
- Static files (images, css, etc) must be stored on an external host like AWS

**Tasks:**

*  [x] Create workspace with GitPod
*  [x] Install dependancies (Django, Psycopg2, gunicorn, etc)
*  [x] Connect Github to Heroku
*  [x] Connect AWS
    * [x] Upload static files to AWS
    * [x] Upload media images to AWS
*  [x] Connect ElephantSQL/PostGres
*  [x] Set up environment variables
*  [x] Ensure app is showing deployed on Heroku

**Comment by saziosu** [comment]
Set up Django, postgresql, gunicorn, etc.
Added the Procfile and set up the config vars in Heroku.
Deployed to Heroku and confirmed this is now loading deployed correctly on Heroku

Used the [Code Institute steps](https://docs.google.com/document/d/1P5CWvS5cYalkQOLeQiijpSViDPogtKM7ZGyqK-yehhQ) for this

**Comment by saziosu** [comment]
Set up the AWS bucket & Policies, however I am waiting until I have some static files before adding this to the project so that I can confirm it is working correctly.

**Comment by saziosu** [comment]
Followed the BA walkthrough to get the static files uploaded to S3
Confirmed that static css etc is now loading correctly on the deployed site in Heroku

**Comment by saziosu** [comment]
Set up the media folder and confirmed that the images uploaded are loading correctly on heroku
