### ISSUE TITLE
USER STORY: View Total Cost

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#10]
**Epic:** #6 

As a **user** I can **see how much total order will cost** so that I can **know if I can afford my purchase**

**Acceptance Criteria:**
* The user must be able to see the exact amount that shipping will cost
* The user must have a grand total listed that adds the full total of all products and shipping costs

**Tasks:**

* [x] Add shipping cost quota
* [x] Allow this to update on the grand total
* [x] Set up grand total to calculate the full price of the order

**Comment by saziosu** [comment]
Much of this was covered on #7 
I changed the shipping cost from 7% of the total order to 30% of the order to provide a more realistic shipping cost.
Prior to this the shipping cost was coming in at less than a dollar, which doesn't really serve much in the way of encouraging users to get free shipping
