### ISSUE TITLE
USER STORY: User can checkout

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#11]
**Epic:** #6 

As a **user** I can **make payments** so that I can **receive my products**

**Acceptance Criteria:**
* Payments must be taken via Stripe
* Stripe keys must be kept as environment variables/secrets
* Users should get an order confirmation page after completing the order

**Tasks:**

* [x] Set up checkout app
* [x] Add models for creating orders
* [x] Set form for entering user data
* [x] Set up Stripe payments
* [x] Set up Stripe on the front end
* [x] Set up the checkout page
* [x] Set up checkout-success page
    * [x] Add order summary to the checkout success page
* [x] Set up confirmation emails

**Comment by saziosu** [comment]
Set up the checkout app
Added the Order and OrderLine items models, followed the Boutique Ado walkthrough for help with this

**Comment by saziosu** [comment]
Added the orderAdmin to admin.py in the checkout app and added a signals.py file for this also

**Comment by saziosu** [comment]
Added forms.py to the checkout app
Added the OrderForm for entering the user information

**Comment by saziosu** [comment]
Added the templates and css folders/files for the the checkout page

**Comment by saziosu** [comment]
Added some updates to the template to include the brand name on the order summary on the checkout

**Comment by saziosu** [comment]
Set up the stripe card elements on the front end along with the corresponding css and js to show the form on the front end for collecting card details

**Comment by saziosu** [comment]
Further added to the stripe_elements.js file and checkout/views.py checkout view to allow for stripe payments.
Tested the initial payment and this is taking on the payment from a test card

**Comment by saziosu** [comment]
Further added to the stripe_elements.js file and checkout/views.py checkout view to allow for stripe payments.
Tested the initial payment and this is taking on the payment from a test card

**Comment by saziosu** [comment]
Added the checkout-success view, template and urls.
Tested this a few times and confirmed that the details are correct on the admin view.

**Comment by saziosu** [comment]
Added an order summary to the checkout success page that shows what was ordered

**Comment by saziosu** [comment]
Added the payment overlay from the walkthrough project to prevent issues with cards requiring authentication

**Comment by saziosu** [comment]
Followed the walkthrough to utilise caching payment data intent on the checkout

**Comment by saziosu** [comment]
Further followed the Boutique Ado walkthrough for completing the Stripe webhook handler

**Comment by saziosu** [comment]
Followed the BA walkthrough again for help with setting up the django-countries for the checkout form

**Comment by saziosu** [comment]
Followed the BA walkthrough again to set up the confirmation emails
The templates were set up and the code for sending them was added to webhook_handler.py
