### ISSUE TITLE
USER STORY: View Product Range

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#13]
**Epic:** #12 

As a **user**, I can **view all available products** so that I can **compare and decide which I want to purchase**

**Acceptance Criteria:**
* The user must be able to see all available products
* The user must be able to see the product image, name and pricing on the front end

**Tasks:**

* [x] Set up products
* [x] Allow user to view these on the front end
* [x] Set pricing and categories on each product

**Comment by saziosu** [comment]
Added the product model and added the products including, prices, descriptions, images etc

**Comment by saziosu** [comment]
Updated models.py to allow for additional fields such as brand and ingredients on the products

**Comment by saziosu** [comment]
Extended products/models.py further to allow for further categorisation such as Brand and heat levels

**Comment by saziosu** [comment]
Added further products including spicy snacks to the database

**Comment by saziosu** [comment]
Updated the products/admin.py to update the plural name in the product admin from 'categorys' to 'categories'
Set up the ProductAdmin, CategoryAdmin and BrandAdmin to update the items listed in the admin for each of them

**Comment by saziosu** [comment]
Hooked up the products/urls.py to render the future templates that I'll be working on next.
Also attached this to the project level urls.py

**Comment by saziosu** [comment]
Changed the heat levels class from a choice field to a regularly category with a friendly name to simplify the process.
Updated products/products.html to allow viewing of all products

**Comment by saziosu** [comment]
Added product detail, views and urls to allow for viewing of the individual product
Included brand, price, description and ingredients along with the image on the product detail
