### ISSUE TITLE
USER STORY: View products by category

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#16]
**Epic:** #12 

As a **user** I can **choose different categories from the front end** so that I can **find the products that I want to purchase**

**Acceptance Criteria:**
* Each product must have a category added
* Users should be able to view all products by category

**Tasks:**

* [x] Add products via the admin
* [x] Allow users to view the products by category
* [x] Users should be able to by category, heat level and brand

**Comment by saziosu** [comment]
Set up the filtering in products/views.py
Added the urls to the nav bar, users can now view the products by type AND/OR by spice level
I have also added the functionality to filter by brand, although the urls are not hooked up to the front end just yet

**Comment by saziosu** [comment]
Added the sorting functionality, this currently works for price.
However for brands, heat_level and category this is currently ordering them by ID which will be tackled soon

**Comment by saziosu** [comment]
Added links to both products.html and product_detail.html
This allows users to quickly view all products that have the same brand or heat level as the individual product

**Comment by saziosu** [comment]
Added further sorting to the products.html template so that further sorting such as by price (high to low or vice versa) or by heat level can be used

**Comment by saziosu** [comment]
Set up the sorting to fix the brands being ordered by the brand ID instead of its name

**Comment by saziosu** [comment]
Having an issue with sorting by heat levels as mentioned in #26 
Closing this off for now as the infrastructure is there and I will come back to the bug at a later date.
