### ISSUE TITLE
USER STORY: View order history

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#19]
**Epic:** #17 

As a **user**, I can **view my order history on my profile** so that I can **track my purchasing**

**Acceptance Criteria:**
* Users could be able to view their previous orders so that they can review their previous purchasing history
* This could be available in their user profile
* This must only be accessible to the user that actually made the respective order.

**Tasks:**

* [x] Set up profile app
* [x] Set up the order history section
* [x] Create a space for this on the user profile
* [ ] Ensure that this is only available to user that created the order

**Comment by saziosu** [comment]
Added the user_profile field to the Order model in the checkout app
This is to link the order with the user profile that created it, and also allow a profile to be created off the order if one does not already exist

**Comment by saziosu** [comment]
Added the order to the profile views.py and added the section for it on the profile template

**Comment by saziosu** [comment]
Followed the Boutique Ado walkthrough further for setting up the order history viewing via the profile
