### ISSUE TITLE
USER STORY: Allow Admin users to create products

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#2]
**Epic:**

As an **Admin**, I can **add products on the front end** so that **I can add further products to my store**

**Acceptance Criteria:**
* The product admin must only be viewable by super users
* The admin user must be able to add products
* The admin user must be able to upload an image for the product

**Tasks:**

* [x] Set up the forms.py to allow the user to add products
* [x] Set up product admin templates
* [x] Wire up the urls
* [x] Secure the view, only to superuser/admin logged in

**Comment by saziosu** [comment]
Set up the products/forms.py file to allow the admin user to add products

**Comment by saziosu** [comment]
Set up the add_product view, templates and urls
This will allow admin users to add a product with the category, brand and heat level on the front end

**Comment by saziosu** [comment]
Added post handler to the add_product view, also wired up the urls on the templates to access the product management from the front end

**Comment by saziosu** [comment]
Followed the Boutique Ado to secure the add_product view
