### ISSUE TITLE
USER STORY: Update user details

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#20]
**Epic:** #17 

As a **user**, I can **update my personal details** so that I can **have them saved for my next purchase**

**Acceptance Criteria:**
* The user should be able to update their personal details on their profile
* Users should be able to update their personal details such as email, address, phone number, etc.

**Tasks:**

* [x] Customise the profile to allow the user to update their details
* [x] Ensure this is writing to the database
* [x] Set up toast messages to ensure adequate feedback
* [ ] Set the user details to default on the checkout form

**Comment by saziosu** [comment]
Added the profile app and added the models for the default information for the user profile
Such as the name, address, email etc.

**Comment by saziosu** [comment]
Updated the views for the profile app and hooked up the url on the base template to render the user's profile

**Comment by saziosu** [comment]
Added the forms.py with a form for updating the user's default shipping information

**Comment by saziosu** [comment]
Updated the profile.html template and profile.css to render the user details form on the front end

**Comment by saziosu** [comment]
Added countryselector.js to resolve color selection issues on the profile form's country input, following the Boutique Ado set up for this

**Comment by saziosu** [comment]
Added the saving of profile info from the checkout to the webhook_handler.py to allow for saving of the profile details via the checkout 'save-info' checkbox
