### ISSUE TITLE
USER STORY: Search Products

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#21]
**Epic:** #12 

As a **user**, I can **search for products** so that I can **find the product I am looking for**

**Acceptance Criteria:**
* The user should be able to search for their desired product
* Users should be able to see matches of their search if they're looking for a specific brand or heat level

**Tasks:**

* [x] Set up Products
* [x] Set up search bar
* [x] Set up search functionality
    * [x] Allow users to search in product fields such as name, description and ingredients
    * [x] Allow users to search by category, brand and heat levels

**Comment by saziosu** [comment]
I have used Q from django.db.models to allow users to search in the product name, description and ingredients

**Comment by saziosu** [comment]
Set up the filtering for brands and heat_levels
I was then able to use Q also to allow searching for specific brands or heat levels
