### ISSUE TITLE
USER STORY: Styling & Layout

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#23]
**Epic:** #22 

As a **User**, I can **view a clean and attractive website** so that I can **have a positive experience**

**Acceptance Criteria:**

**Tasks:**

**Acceptance Criteria:**

- The css, colours used and images should be fitting with the theme of the website
- The structure of the posts should be well laid out and consistent across the site

**Tasks:**

*  [x] Add html and templated structure and layout
*  [x] Update css and bootstrap with improved styling
* [x] Add and style custom 404 and 403 pages.
* [ ] Add favicon

**Comment by saziosu** [comment]
Added the aullauth templates and the base.html
Followed the Code Institute Boutique Ado process for this to give a good starting point.
These will be edited in future to bring this in line with the theme of this website.

**Comment by saziosu** [comment]
Added the home app for the homepage
Added the index.html for this and added the planned hero image for the website.
Followed the Boutique Ado walkthrough as a starting point for setting up the site.
Again, this will be changed to suit the needs of the website at a later date.

**Comment by saziosu** [comment]
Followed the Boutique Ado set up for the header and homepage css, added my own image and font choices to customise the site.
This will be further changed in future to personalise the website

**Comment by saziosu** [comment]
Added the main nav header and mobile header.
Again followed the Boutique Ado walkthrough steps for this, however I customised this further to keep in line with the website theme

**Comment by saziosu** [comment]
Added the cart and all products & product_detail templates
I also followed the Boutique Ado walkthrough for this - making edits along the way to match my website theme

**Comment by saziosu** [comment]
Followed the boutique Ado walkthroughs for the User Profiles and Product admins also
Will be editing these further at a later date

**Comment by saziosu** [comment]
Followed the BA walkthrough to update the base.css to make the site more mobile friendly
Also updated the links in mobile-top-header.html and main-nav.html

**Comment by saziosu** [comment]
Followed the Boutique Ado walkthrough to refactor the shopping cart for smaller screen sizes
I also used the final walkthrough's final codebase to resolve the quantity buttons issues with the product quantity javascript

**Comment by saziosu** [comment]
Set up the 403 and 404 error pages
Also added a 500 error page to the site

**Comment by saziosu** [comment]
Updated the products and product_detail templates to include the Staff favourite marker to let users know that the team behind the store loved a particular product

**Comment by saziosu** [comment]
Added a transparent background behind the text on the hero section to make it better readability

**Comment by saziosu** [comment]
Added a footer to base.html
Took some time to get this set to the bottom of the page for pages that don't have as much content, such as the sign up page

**Comment by saziosu** [comment]
Had some issues with the mailchimp newsletter being two wide and causing issues with side scrolling on the contact page.
I added some media queries to base.css to reduce this down on smaller screen sizes

**Comment by saziosu** [comment]
Added the favicon to personalise the site
