### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#29]
**Epic:** #28 

As a **User**, I can **contact the website admins** so that I can **resolve any issues with my order**

**Acceptance Criteria:**
* The user should be able to contact the owners of the store from the website itself via a contact form
* The admin user should be able to view these contact form submissions on the front end

**Tasks:**

* [x] Set up Contact App
    * [x] Add this app to the installed apps in settings.py
* [x] Add a contact form
* [x] Add the form to a template on the front end
* [x] Add template on the front end for the admin user to view the contact form submissions
* [x] Link the contact form and submissions to the navbars
* [x] Secure the view for viewing the contact form submissions to only superusers

**Comment by saziosu** [comment]
Added the Contact model, along with the ContactForm modelform
I used crispyforms helpers to set up the contact form and this is now working great

Next I will be making the view to allow the admin user to view the contact form submissions on the front end

**Comment by saziosu** [comment]
Added the  ContactView for viewing the contact form submissions.
Also added the urls and template for viewing this.
I will also be securing the view so that only superusers can access this view

**Comment by saziosu** [comment]
Secured the ContactView so that only superusers can view the contact form submissions

**Comment by saziosu** [comment]
Added a contact form success page after the user successfully adds a contact form submisson
