### ISSUE TITLE
USER STORY: Allow Admin users to edit products

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#3]
**Epic:**

As an **Admin**, I can **update products on the front end** so that I **can update details on the products**

**Acceptance Criteria:**
* The admin user must be able to update products on the front end
* The admin user must be able to change the image of the product
* This must only be accessible to users logged in as a superuser

**Tasks:**

* [x] Set up edit templates
* [x] Add product editing view
* [x] Wire up url
* [x] Ensure this writes to the database
* [x] Add links to the product pages/templates to allow superusers to edit products on front end
* [ ] Secure the view, only to superuser/admin logged in

**Comment by saziosu** [comment]
Added the editing template, view and url for editing a product in the products app.
Followed the Boutique Ado walkthrough for this

**Comment by saziosu** [comment]
Tested the editing and confirmed this is writing to the db correctly

**Comment by saziosu** [comment]
Also added the links on the front end for the superuser to  edit and/or delete the products.

**Comment by saziosu** [comment]
Followed the Boutique Ado to secure the edit_product view
