### ISSUE TITLE
USER STORY: Allow users to Add product reviews

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#32]
**Epic:** #28 

As a **user**, I can **leave reviews on a product** so that I can **give my opinion on the product**

**Acceptance Criteria:**
- The user must be logged in to comment or review on the product
- The user should have ordered the product before to be capable of leaving a review
- The comment should include the username and the date it was left

**Tasks:**

* [x] Add the ProductReview model to products app
* [x] Add the view, including restricting this to users that have ordered it before
   * [x] Add to the view so that users can only review the product once
* [x] Add the review form template

**Comment by saziosu** [comment]
Added the ProductReview model which collects the entries from the product reviews.
Set up the ProductReviewForm and the view for submitting product reviews.
Also added the template to render the form

Currently the user only has to be logged in to review the product.
I will be looking into restricting this view to users who have purchased the product once all testing confirms the form works as expected.

**Comment by saziosu** [comment]
Further secured the review_product view to only allow users that have purchased the product before to be able to leave a review
If you try to access the review form without having purchased it before, there is an error message displayed and the user is redirected back to the product detail page.

**Comment by saziosu** [comment]
Restricted the product view further so that users can only review a product once time
