### ISSUE TITLE
USER STORY: User can signup for newsletter

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#33]
**Epic:** #28 

As a **user**, I can **sign up for a newsletter** so that I can **keep up to date on news from my favourite store**

**Acceptance Criteria:**
- The user could be able to enter their email address and sign up for a newsletter
- The newsletter can be provided via mailchimp

**Tasks:**

* [x] Sign up for mailchimp
* [x] Build the newsletter signup in the MailChimp account
* [x] Add the code to the template

**Comment by saziosu** [comment]
Added the mailchimp newletter signup to the Contact Us page.
