### ISSUE TITLE
USER STORY: Allow admin users to delete products

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#4]
**Epic:**

As an **Admin**, I can **delete products on the front end** so that I can **manage my store**

**Acceptance Criteria:**
* This must only be available to users logged in as superuser
* The product must be successfully deleted
* The messaging should confirm that the product has been deleted

**Tasks:**

* [x] Add urls for deleting
* [x] Add view for product deletion
* [x] Ensure this deletes the selected product
* [x] Add the links for superusers to delete products on front end
* [ ] Secure the view, only to superuser/admin logged in

**Comment by saziosu** [comment]
Added the view and url for deleting products.
Confirmed this works on a test product.
Also added the links on the front end for the superuser to  edit and/or delete the products.

**Comment by saziosu** [comment]
Followed the Boutique Ado to secure the delete_product view
