### ISSUE TITLE
USER STORY: Add products to shopping cart

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#7]
**Epic:** #5 

As a **user** I can **add products to my cart** so that I can **purchase them**

**Acceptance Criteria:**
* The user must be able to add products to their shopping cart
* Toast messages should confirm to the user that the product has been added to the cart

**Tasks:**

* [x] Set up the cart app
* [x] Set up views to handle the cart
* [x] Set up cart template
* [x] Allow users to add products to cart from the  product detail page

**Comment by saziosu** [comment]
Set up the cart app and wired up the templates, urls and settings to allow the cart to be viewed
This is currently using the template from the homepage, and will be customized further

**Comment by saziosu** [comment]
Added contexts.py to allow cart_items to be accessed elsewhere in the django project by adding it to settings.py
Set up the cart to show no items in the cart

**Comment by saziosu** [comment]
Added the add_to_cart view to handle adding items to the shopping cart
Added the form to product_detail.html
Wired up the urls for this also

**Comment by saziosu** [comment]
Added to contexts.py to allow cart items to show in the cart page

**Comment by saziosu** [comment]
Updated the cart.html to display the items on a table
I added the brand name as links so encourage shoppers to view the products from the same range.
