### ISSUE TITLE
USER STORY: Remove products from Cart

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#8]
**Epic:** #6 

As a **user** I can **remove items from my cart** so that I can **purchase something else**

**Acceptance Criteria:**
* The user must be able to remove items from their cart
* Toast messages should confirm that the item has been removed

**Tasks:**

* [x] Set up the cart
* [x] Add a 'remove' button/link to the item
* [x] Add message confirmation that the item has been removed

**Comment by saziosu** [comment]
Remove links on the cart have been added
Confirmed that these work correctly
Also added the messages for confirmation that the item has been removed from the cart
