### ISSUE TITLE
USER STORY: Edit product quantity in cart

### ISSUE THREAD

**Issue by saziosu** [saziosu/flame-masters#9]
**Epic:** #6 

As a **user** I can **update the number of items in my cart** so that I can **easily purchase the correct number of items**

**Acceptance Criteria:**
* The user must be able to edit the quantity of products in their cart
    * They must be able to increase or decrease this quantity
* The user should be able to choose how many items to add to their cart

**Tasks:**

* [x] Set up the cart, views, templates, etc.
* [x] Add quantity links/buttons in the cart for each item
    * [x] Add the same to the process of adding to cart from the product detail page
* [x] Add quantity links to allow removing items from the cart

**Comment by saziosu** [comment]
Added the buttons on the product detail page to increase and decrease the number of items to be added to the cart on the product detail
Will also be adding this to the cart itself shortly so that can be edited prior to checking out

**Comment by saziosu** [comment]
Added the buttons to increase or decrease the quantity in the shopping cart, along with the javascript required for these buttons to increase/decrease the number

**Comment by saziosu** [comment]
Added the modify_cart and modify_cart views to the cart app
The quantity of items can now be completed, along with removing items entirely from the cart

**Comment by saziosu** [comment]
Added the cart_tools.py to calculate the subtotals
